name: DiceRoll
main: com.obscurityGames.diceRoll.Main
version: 1.0
api-version: 1.14
commands:  
    roll:
        description: roll a die or multiple dice.
        usage: /roll [number of sides] (number of dice)
        permission: diceroll.roll
        permission-message: You don't have the diceroll.roll permission
permissions:
    diceroll.roll:
        description: Allows you to roll dice
        default: true
softdepend: [RoleplayChat]
